//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class GMS_WorkOrder
    {
        public int ID { get; set; }
        public Nullable<int> SyncWorkOrderID { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public Nullable<int> RailWay_ID { get; set; }
        public string RailWayName { get; set; }
        public Nullable<int> RailWayType { get; set; }
        public Nullable<int> OU_ID { get; set; }
        public string OUName { get; set; }
        public string WorkPlace { get; set; }
        public string Content { get; set; }
        public string WorkLeader { get; set; }
        public string Operator { get; set; }
        public string ProtectionMan { get; set; }
        public Nullable<System.DateTime> SkylightDate { get; set; }
        public string WorkContent { get; set; }
        public Nullable<int> WorkType { get; set; }
        public string Leader_ID { get; set; }
        public string Worker_ID { get; set; }
    }
}
