//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class GMS_WorkOrderEquipment
    {
        public int ID { get; set; }
        public int WorkOrder_Id { get; set; }
        public int Equipment_ID { get; set; }
        public string EquipmentName { get; set; }
        public Nullable<int> IsInPos { get; set; }
        public Nullable<System.DateTime> InPosDt { get; set; }
        public Nullable<int> IsInPosConfirm { get; set; }
        public Nullable<System.DateTime> InPosConfirmDt { get; set; }
        public string InPosConfirmDesc { get; set; }
        public Nullable<int> IsAtchOrdered { get; set; }
        public Nullable<System.DateTime> AtchOrderedDt { get; set; }
        public Nullable<int> IsAtched { get; set; }
        public Nullable<System.DateTime> AtchedDt { get; set; }
        public Nullable<int> IsAtchConfirm { get; set; }
        public Nullable<System.DateTime> AtchConfirmDt { get; set; }
        public string AtchConfirmDesc { get; set; }
        public Nullable<int> IsRemoveOrdered { get; set; }
        public Nullable<System.DateTime> RemoveOrderedDt { get; set; }
        public Nullable<int> IsRemoved { get; set; }
        public Nullable<System.DateTime> RemovedDt { get; set; }
        public Nullable<int> IsRemoveConfirm { get; set; }
        public Nullable<System.DateTime> RemoveConfirmDt { get; set; }
        public string RemoveConfirmDesc { get; set; }
    }
}
